<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Channel extends Model
{
    use SoftDeletes;

    protected $dates = ["deleted_at"];

    public function draws() {
        return $this->hasMany('\App\Draw');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($channel) {
            $channel->draws()->delete();
        });
    }
}
