<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Channel extends Model
{
    use SoftDeletes;

    protected $dates = ["deleted_at"];

    public function draws() {
        return $this->hasMany('\App\Draw');
    }

    public function remainingDraws() {
        $current_time = Carbon::now()->format('H:i');
        return $this->draws()->whereRaw('time(draw_time) > time(?)', array($current_time))->get();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($channel) {
            $channel->draws()->delete();
        });
    }
}
