<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Draw extends Model
{
    use SoftDeletes;

    protected $dates = ["deleted_at"];

    public function channel() {
        return $this->belongsTo('\App\Channel');
    }

    public function transactions() {
        return $this->hasMany('\App\Transaction');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($draw) {

        });
    }
}
