<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transaction extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    public function amount() {
        return $this->donations()->sum('amount');
    }

    public function ngo_print_string() {
        $ret = "";
        foreach($this->donations as $donation) {
            $ret .= $donation->ngo->description.", ";
        }
        return $ret;
    }

    public function donations() {
        return $this->hasMany('\App\Donation');
    }

    public function draw() {
        return $this->belongsTo('\App\Draw');
    }

    public function center() {
        return $this->belongsTo('\App\Center');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($transaction) {
            $transaction->donations()->delete();
        });
    }
}
